dist: trusty

sudo: required

language: go

git:
  depth: 1

matrix:
  fast_finish: false

os:
  - linux
  - osx

go:
  - "1.14.2"
  - master

before_script:
  - go get github.com/bradfitz/slice

script:
  - go build awesome.go
